server:
  port: 8080

spring:
  redis:
    password: 123456
    port: 6379
    host: 172.25.63.38
boot:
  bloom:
    name: 'test'
#boot:
#  redisson:
#    mode: Single
#    single:
#      address: "172.25.63.38:6379"
