server:
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: hocgin
    druid:
      validation-query: SELECT 1
      test-while-idle: true
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/**/xml/*.xml
boot:
  message:
    type: Redis
