logging:
  level:
    root: WARN
    com.alibaba.nacos: WARN
    in.hocg.rabbit: DEBUG
    in.hocg: DEBUG
  config: classpath:log4j2-boot-local.xml
  file:
    path: /Users/hocgin/Downloads/logs/app/${spring.application.name:unknown}
    name: ${logging.file.path}/${spring.application.name:unknown}.log
