server:
  port: 20002
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
logging:
  level:
    root: debug
boot:
  sso:
    client:
      ignore-urls:
        - '/ignore'
debug: true
security:
  oauth2:
    hostname: http://sso.hocgin.local:20000
    resource:
      token-info-uri: ${security.oauth2.hostname}/oauth/check_token
      user-info-uri: ${security.oauth2.hostname}/oauth/user
      prefer-token-info: false
    client:
      client-id: client_example
      client-secret: hocgin
      user-authorization-uri: ${security.oauth2.hostname}/oauth/authorize
      access-token-uri: ${security.oauth2.hostname}/oauth/token
    authorization:
      check-token-access: ${security.oauth2.hostname}/oauth/check_token
