name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          server-id: github
          java-version: 1.8

      # 缓存 Maven 仓库
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - name: Deploy to Github Package Registry
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn deploy -DaltDeploymentRepository="${REPO}" -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Sonatype Package Registry
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>\${env.ID}</id><username>\${env.USERNAME}</username><password>\${env.PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="\${env.ID}::default::\${env.URL}"
          mvn deploy -DaltDeploymentRepository="${REPO}" -DskipTests
        env:
          ID: sonatype-snapshots
          URL: https://oss.sonatype.org/content/repositories/snapshots
          USERNAME: hocgin
          PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Deploy to Alibaba Package Registry
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>\${env.ID}</id><username>\${env.USERNAME}</username><password>\${env.PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="\${env.ID}::default::\${env.URL}"
          mvn deploy -P release -DaltDeploymentRepository="${REPO}" -DskipTests
        env:
          ID: rdc-releases
          URL: https://packages.aliyun.com/maven/repository/2026582-release-AuUWIo
          USERNAME: 5f3fc340209ad8bf48f5dd13
          PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
