name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '*.md'
      - '*.editorconfig'
      - '*.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish Package Registry
        run: |
          SNAPSHOT_REPO="\${env.MAVEN_SERVER_ID}::default::\${env.SNAPSHOT_URL}"
          RELEASE_REPO="\${env.MAVEN_SERVER_ID}::default::\${env.RELEASE_URL}"
          mvn --batch-mode deploy -P release -DaltDeploymentRepository="${RELEASE_REPO}" -DaltSnapshotDeploymentRepository="${SNAPSHOT_REPO}" -DskipTests
        env:
          SNAPSHOT_URL: https://oss.sonatype.org/content/repositories/snapshots
          RELEASE_URL: https://oss.sonatype.org/service/local/staging/deploy/maven2
          MAVEN_SERVER_ID: sonatype
          MAVEN_USERNAME: hocgin
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      # 企业微信通知
      - id: wx_prep
        run: |
          echo ::set-output name=wx_created::$(TZ=Asia/Shanghai date -d @`date +%s` "+%Y-%m-%d %H:%M:%S")
          GITHUB_REF=${{github.base_ref}}
          echo ::set-output name=wx_base_ref::$(echo ${GITHUB_REF#refs/heads/})
          GITHUB_REF=${{github.event.ref}}
          echo ::set-output name=wx_target_ref::$(echo ${GITHUB_REF#refs/heads/})
      - name: WeChat Work Notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "🎉**【[${{ github.repository }}](https://github.com/${{ github.repository }})】** \n
          \n
          🏃 [@${{ github.actor }}](https://github.com/${{ github.actor }})\n
          🕐 <font color=\"comment\">${{ steps.wx_prep.outputs.wx_created }}</font> \n
          🔧 <font color=\"warning\">${{ steps.wx_prep.outputs.wx_base_ref || '∅' }} -> ${{ steps.wx_prep.outputs.wx_target_ref }}</font> \n
          📝 <font color=\"comment\"> ${{ github.event.head_commit.message }}</font> \n
          \n
          [查看详情](https://www.hocgin.top)
          "

