server:
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://mysql.klxuexi.net:3306/edu_sample_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      validation-query: SELECT 1
      test-while-idle: true
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/**/xml/*.xml
